from dataclasses import dataclass
import re

@dataclass
class Classification:
    category: str; subcategory: str; department: str; priority: str; urgency_score: int; confidence: float; reason: str; suggested_staff_type: str; provider_used: str="rule_based"; model_name: str|None=None; ai_status: str="fallback"; processing_time: float|None=None

RULES = [
    # Immediate hazards are checked first so a broad match never downgrades safety.
    (r"chemical spill|acid leak|toxic|biohazard", "Lab Safety", "Hazardous Material Incident", "CRITICAL", 10, "Hazmat Specialist"),
    (r"fume hood|exhaust hood|chemical ventilation", "Lab Safety", "Lab Ventilation Failure", "CRITICAL", 9, "Lab Safety Officer"),
    (r"compressed gas|cylinder|nitrogen|argon|helium", "Lab Safety", "Gas Cylinder Hazard", "CRITICAL", 9, "Safety Specialist"),
    (r"freezer -80|cold store|sample storage|deep freeze", "Lab Support", "Sample Storage Failure", "CRITICAL", 9, "Refrigeration Specialist"),
    (r"gas leak|lpg smell", "Safety", "Gas Leakage Hazard", "CRITICAL", 10, "Safety Specialist"),
    (r"fire alarm|smoke detector|beeping alarm", "Security", "Fire Safety System", "CRITICAL", 10, "Safety Officer"),
    (r"lift stuck|trapped in (an? )?(elevator|lift)|lift emergency", "Elevator", "Elevator Emergency", "CRITICAL", 10, "Elevator Technician"),
    (r"server down|datacenter|rack failure", "IT Support", "Infrastructure Failure", "CRITICAL", 10, "Systems Administrator"),
    (r"pipe burst|flooding|main leak", "Plumbing", "Major Water Hazard", "CRITICAL", 10, "Plumber"),
    (r"wire|shock|sparks?|fire|exposed", "Electrical", "Electrical Hazard", "CRITICAL", 10, "Electrician"),
    (r"blackout|power outage|no power|breaker", "Electrical", "Power Outage", "CRITICAL", 9, "Electrician"),
    (r"lost and found|unattended bag|suspicious package", "Security", "Security Investigation", "CRITICAL", 10, "Security Officer"),
    (r"security (issue|breach|incident)|security gate|theft|break in|unauthorized", "Security", "Security Breach", "CRITICAL", 9, "Security Officer"),
    (r"spill|chemical leak|hazardous liquid", "Cleaning", "Hazardous Spill", "CRITICAL", 9, "Hazmat Cleaning Staff"),
    (r"central cooling|chiller plant", "HVAC", "Central Cooling Failure", "CRITICAL", 9, "HVAC Engineer"),
    # Electrical, plumbing and climate.
    (r"short circuit|flicker|burning smell", "Electrical", "Short Circuit / Burn", "HIGH", 8, "Electrician"),
    (r"ups|backup battery|generator|inverter", "Electrical", "Backup Power", "HIGH", 8, "Electrical Engineer"),
    (r"voltage stabilizer|transformer|high voltage", "Electrical", "Industrial Electrical Support", "HIGH", 8, "Electrical Engineer"),
    (r"stage power|event cabling|generator for event", "Electrical", "Temporary Event Power", "HIGH", 8, "Electrician"),
    (r"electric|power|fan|light|tube light|bulb", "Electrical", "Power / Lighting", "HIGH", 7, "Electrician"),
    (r"street light|pathway light|pole light|outdoor lighting", "Electrical", "Outdoor Lighting", "MEDIUM", 5, "Electrician"),
    (r"ev charger|charging station|electric vehicle point", "Electrical", "EV Infrastructure", "MEDIUM", 6, "Electrician"),
    (r"socket|plug|outlet|switchboard", "Electrical", "Sockets & Switches", "MEDIUM", 6, "Electrician"),
    (r"ac.*(leak|drip)|water from ac|air conditioner.*(leak|drip)", "HVAC", "AC Leakage", "HIGH", 7, "HVAC Technician"),
    (r"ac.*(not cooling|hot)|air conditioner.*(not cooling|hot)|ac cooling", "HVAC", "AC Performance", "MEDIUM", 6, "HVAC Technician"),
    (r"ac noise|ac smell|ac gas", "HVAC", "AC Maintenance", "MEDIUM", 5, "HVAC Technician"),
    (r"ventilation|choke|hvac filter|exhaust", "HVAC", "Air Ventilation", "MEDIUM", 5, "HVAC Technician"),
    (r"heater|radiator|room heating", "HVAC", "Heating Issue", "MEDIUM", 5, "HVAC Technician"),
    (r"clog|overflow|blocked toilet|flush", "Plumbing", "Sanitation / Clogging", "HIGH", 8, "Plumber"),
    (r"no water|dry tap|low pressure", "Plumbing", "Water Supply Issue", "HIGH", 7, "Plumber"),
    (r"sewage|foul smell|drainage", "Plumbing", "Sewage Issue", "HIGH", 8, "Plumber"),
    (r"grease trap|kitchen drain clog", "Plumbing", "Kitchen Drainage", "HIGH", 7, "Plumber"),
    (r"storm drain|gutter blocked|rainwater drain", "Plumbing", "Stormwater Drainage", "HIGH", 7, "Plumber"),
    (r"water cooler|purifier|ro plant|dispenser", "Plumbing", "Drinking Water System", "MEDIUM", 6, "RO Maintenance Technician"),
    (r"geyser|water heater", "Plumbing", "Water Heating", "MEDIUM", 5, "Plumber"),
    (r"washbasin|sink|faucet", "Plumbing", "Fixture Repair", "LOW", 4, "Plumber"),
    (r"leak|tap|drain|water|plumb", "Plumbing", "Water Leakage", "HIGH", 8, "Plumber"),
    # IT and AV.
    (r"wifi|internet|network|lan|router", "IT Support", "Network Connectivity", "HIGH", 7, "Network Technician"),
    (r"biometric|attendance machine|card reader", "IT Support", "Access Control Hardware", "HIGH", 7, "IT Specialist"),
    (r"cctv camera|surveillance DVR|nvr", "IT Support", "Security Systems IT", "HIGH", 8, "CCTV Engineer"),
    (r"public address|pa system|announcement speaker", "IT Support", "PA System Repair", "HIGH", 7, "AV / IT Technician"),
    (r"projector|display|hdmi|av system|mic|speaker", "IT Support", "AV Equipment", "MEDIUM", 6, "AV Specialist"),
    (r"amplifier|sound board|mixer|mic feedback", "AV Support", "Audio System Issue", "MEDIUM", 6, "AV Specialist"),
    (r"auditorium stage|podium|stage lighting|curtain", "AV Support", "Stage Maintenance", "MEDIUM", 5, "AV Specialist"),
    (r"digital signage|kiosk|interactive display", "IT Support", "Public Displays", "MEDIUM", 5, "IT Support Technician"),
    (r"computer|pc|laptop|desktop|monitor", "IT Support", "Hardware Issue", "MEDIUM", 5, "IT Support Technician"),
    (r"software|os crash|virus|malware", "IT Support", "Software Support", "MEDIUM", 5, "IT Support Specialist"),
    (r"printer|scanner|photocopier|toner", "IT Support", "Peripheral Maintenance", "LOW", 4, "IT Support Technician"),
    # Buildings, services, safety and operations.
    (r"broken door|door handle|lock broken|stuck door", "Carpentry", "Door / Lock Repair", "HIGH", 7, "Carpenter"),
    (r"broken window|glass shattered|cracked pane", "Carpentry", "Glass / Window Hazard", "HIGH", 8, "Glazier / Carpenter"),
    (r"loading dock|shutter door|rolling shutter", "Carpentry", "Dock Door Maintenance", "HIGH", 7, "Mechanical / Carpenter"),
    (r"chair broken|desk damaged|table loose|furniture", "Carpentry", "Furniture Repair", "LOW", 3, "Carpenter"),
    (r"cupboard|cabinet|drawer stuck|shelf", "Carpentry", "Storage Repairs", "LOW", 3, "Carpenter"),
    (r"seating|broken auditorium chairs|loose bench", "Carpentry", "Public Seating Repair", "LOW", 4, "Carpenter"),
    (r"wall crack|ceiling damage|plaster fall", "Civil Work", "Structural Maintenance", "HIGH", 7, "Civil Mason"),
    (r"roof leak|seepage|damp wall", "Civil Work", "Waterproofing / Seepage", "HIGH", 7, "Civil Contractor"),
    (r"wheelchair ramp|accessibility|handrail loose", "Civil Work", "Accessibility Maintenance", "HIGH", 7, "Civil Mason"),
    (r"warehouse rack|storage shelving|heavy rack", "Civil Work", "Storage Structural Safety", "HIGH", 8, "Civil Contractor"),
    (r"pothole|road damage|asphalt repair|driveway", "Civil Work", "Road & Pathway Repair", "LOW", 4, "Civil Contractor"),
    (r"tiles broken|flooring loose|carpet tear", "Civil Work", "Flooring Issue", "LOW", 4, "Civil Mason"),
    (r"paint peeling|wall touchup", "Civil Work", "Painting Work", "LOW", 2, "Painter"),
    (r"boundary wall|fence broken|barbed wire", "Security", "Perimeter Breach Hazard", "HIGH", 7, "Civil / Security Team"),
    (r"fire hose|sprinkler|extinguisher expired", "Security", "Fire Equipment", "HIGH", 8, "Fire Safety Inspector"),
    (r"emergency exit blocked|evacuation route", "Security", "Safety Compliance", "HIGH", 8, "Safety Officer"),
    (r"stray animal|dog inside|snake|monkey", "Security", "Animal Hazard", "HIGH", 8, "Security / Control Team"),
    (r"key lost|duplicate key|access card lost", "Security", "Access Management", "MEDIUM", 5, "Security Administrator"),
    (r"keycard|smart lock|solenoid lock", "Security", "Digital Access Lock", "HIGH", 7, "IT / Security Specialist"),
    (r"lift noise|lift jerky|elevator buttons", "Elevator", "Elevator Maintenance", "HIGH", 7, "Elevator Technician"),
    (r"escalator stopped|escalator issue", "Elevator", "Escalator Repair", "MEDIUM", 5, "Elevator Technician"),
    # Campus life, labs, food, grounds and transport.
    (r"lab equipment|microscope|centrifuge|autoclave|spectrometer", "Lab Support", "Lab Instrument Repair", "HIGH", 7, "Lab Technician"),
    (r"chemical odor|strange smell in lab|toxic fumes", "Lab Safety", "Air Contamination", "HIGH", 8, "Lab Safety Officer"),
    (r"eyewash station|safety shower|chemical kit", "Lab Safety", "Emergency Station Inspection", "HIGH", 7, "Safety Inspector"),
    (r"soldering|3d printer|cnc machine|laser cutter", "Workshop", "Workshop Machinery Failure", "MEDIUM", 6, "Workshop Technician"),
    (r"deionized water|di water|distilled water plant", "Lab Support", "Specialized Water System", "MEDIUM", 5, "Lab Technician"),
    (r"food quality|spoiled food|food.*spoiled|stale food|food.*stale|food poison", "Food Safety", "Food Quality Issue", "HIGH", 8, "Food Safety Inspector"),
    (r"fly|flies|insects in cafeteria|food pests", "Pest Control", "Food Area Hygiene", "HIGH", 7, "Pest Control Specialist"),
    (r"exhaust canopy|grease duct|kitchen chimney", "Pantry", "Kitchen Fire Hazard", "HIGH", 8, "HVAC Technician"),
    (r"cold room|walk in freezer|cafeteria fridge", "Pantry", "Commercial Refrigeration", "HIGH", 8, "HVAC Technician"),
    (r"dish washer|commercial dishwasher|utensil clean", "Pantry", "Sanitation Equipment", "MEDIUM", 5, "Appliance Technician"),
    (r"pantry water|boiler|hot water dispenser", "Pantry", "Pantry Appliance", "LOW", 4, "Appliance Technician"),
    (r"fridge|refrigerator|freezer", "Appliance Repair", "Kitchen Appliances", "MEDIUM", 5, "Appliance Technician"),
    (r"microwave|oven|induction|pantry equipment", "Appliance Repair", "Kitchen Appliances", "MEDIUM", 4, "Appliance Technician"),
    (r"coffee machine|vending machine", "Appliance Repair", "Vendor Equipment", "LOW", 3, "Vendor Technician"),
    (r"pest|termite|cockroach|rodent|rat|bedbug", "Pest Control", "Pest Infestation", "MEDIUM", 6, "Pest Control Specialist"),
    (r"dirty washroom|dirty toilet|restroom clean", "Cleaning", "Sanitation Cleaning", "HIGH", 7, "Cleaning Staff"),
    (r"clean|garbage|waste|trash|dustbin", "Cleaning", "Waste Clearance", "MEDIUM", 4, "Cleaning Staff"),
    (r"hazardous waste|chemical disposal|e-waste", "Cleaning", "Specialized Waste Disposal", "MEDIUM", 6, "Hazmat / Waste Team"),
    (r"dust|mopping|vacuum|floor dirty", "Cleaning", "General Housekeeping", "LOW", 3, "Cleaning Staff"),
    (r"sanitizer refill|soap empty|tissue refill", "Cleaning", "Consumables Restock", "LOW", 2, "Cleaning Staff"),
    (r"stain|window cleaning|facade clean", "Cleaning", "Deep Cleaning", "LOW", 3, "Deep Cleaning Staff"),
    (r"gardening|overgrown grass|tree fallen", "Landscaping", "Groundskeeping", "LOW", 3, "Gardener"),
    (r"tree branch|falling tree|hazardous tree|stump", "Landscaping", "Tree Hazard", "HIGH", 8, "Groundskeeping / Arborist"),
    (r"sprinkler system|irrigation|lawn watering", "Landscaping", "Irrigation Repair", "LOW", 3, "Gardener"),
    (r"snow|ice hazard|slippery walkway", "Groundskeeping", "Hazard Clearing", "HIGH", 8, "Groundskeeping Team"),
    (r"shuttle bus|campus transport|vehicle breakdown", "Transport", "Vehicle Service", "HIGH", 7, "Fleet Manager"),
    (r"parking dispute|blocked vehicle", "Security", "Parking Management", "LOW", 3, "Parking Attendant"),
    (r"forklift|pallet jack|material handling", "Logistics", "Equipment Maintenance", "MEDIUM", 6, "Equipment Technician"),
    (r"projector screen|whiteboard|noticeboard", "General Maintenance", "Classroom / Office Setup", "LOW", 3, "Handyman"),
    (r"flagpole|signage.*broken|broken signage|hoarding loose", "Civil Work", "Exterior Structures", "LOW", 3, "Handyman"),
    (r"noise complaint|loud music|disturbance", "General Administration", "Policy Compliance", "MEDIUM", 5, "Campus Admin"),
]
def classify(text: str) -> Classification:
    lowered=text.lower()
    for pattern,category,subcategory,priority,score,staff in RULES:
        if re.search(pattern,lowered):
            return Classification(category,subcategory,category,priority,score,.78,f"Detected {subcategory.lower()} keywords.",staff)
    return Classification("General Administration","General","General Administration","MEDIUM",4,.40,"No specific rule matched; review recommended.","General Staff")
