"use client";
<<<<<<< HEAD
import { ChangeEvent, FormEvent, useState } from "react";
import { ImagePlus, Send, Video } from "lucide-react";
import { api, setToken } from "../../../lib/api";
import { AppShell } from "../../../components/app-shell";
export default function NewComplaint(){const [message,setMessage]=useState("");const [image,setImage]=useState("");const [video,setVideo]=useState("");const [busy,setBusy]=useState(false);async function upload(e:ChangeEvent<HTMLInputElement>,kind:"image"|"video"){const file=e.target.files?.[0];if(!file)return;const max=kind==="image"?2:5;if(file.size>max*1024*1024){setMessage(`${kind === "image" ? "Photo" : "Video"} must be ${max} MB or less.`);return}setBusy(true);try{const data=new FormData();data.append("file",file);const r=await api.post(`/uploads/${kind}`,data);kind==="image"?setImage(r.data.data.url):setVideo(r.data.data.url);setMessage(`${kind === "image" ? "Photo" : "Video"} attached.`)}catch{setMessage("Upload failed. Check the file type and size.")}finally{setBusy(false)}}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const t=sessionStorage.getItem("campusos_access");if(!t){location.href="/login";return}setToken(t);const f=new FormData(e.currentTarget);try{const r=await api.post("/complaints",{title:f.get("title"),description:f.get("description"),location:f.get("location"),building:f.get("building")||null,room_number:f.get("room")||null,image_url:image||null,video_url:video||null});setMessage(`Submitted ${r.data.data.reference_no}. The assigned expert will be able to view your attachments.`);e.currentTarget.reset();setImage("");setVideo("")}catch{setMessage("Unable to submit. Please check the fields and try again.")}}return <AppShell title="Raise an issue"><form className="card" onSubmit={submit} style={{maxWidth:680,padding:22}}><p className="subtle">Describe the issue. AI suggests the department and priority; your assigned expert can view attached evidence.</p><label>Issue title</label><input name="title" placeholder="e.g. Water leaking from bathroom tap" minLength={4} required/><label>What’s happening?</label><textarea name="description" placeholder="Add enough detail for the service team…" minLength={10} required rows={5}/><label>Location</label><input name="location" placeholder="Hostel Block A" required/><label>Building / room</label><input name="building" placeholder="Building"/><input name="room" placeholder="Room number (optional)"/><div className="split"><label className="button ghost" style={{cursor:"pointer"}}><ImagePlus size={16}/>{image?"Photo attached":"Attach photo (max 2 MB)"}<input type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>upload(e,"image")}/></label><label className="button ghost" style={{cursor:"pointer"}}><Video size={16}/>{video?"Video attached":"Attach video (max 5 MB)"}<input type="file" accept="video/mp4,video/quicktime,video/webm" hidden onChange={e=>upload(e,"video")}/></label></div>{message&&<p className="card" style={{padding:10,margin:"14px 0",background:"#ecfdf3"}}>{message}</p>}<button className="button" disabled={busy}><Send size={16}/>{busy?"Uploading…":"Submit complaint"}</button></form></AppShell>}
=======
import {FormEvent,useState} from "react";import {Send} from "lucide-react";import {api,setToken} from "../../../lib/api";import {AppShell} from "../../../components/app-shell";
export default function NewComplaint(){const [message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const t=sessionStorage.getItem("campusos_access");if(!t){location.href="/login";return}setToken(t);const f=new FormData(e.currentTarget);try{const r=await api.post("/complaints",{title:f.get("title"),description:f.get("description"),location:f.get("location"),building:f.get("building")||null,room_number:f.get("room")||null});setMessage(`Submitted ${r.data.data.reference_no}. AI classification is complete.`);e.currentTarget.reset()}catch{setMessage("Unable to submit. Please check the fields and try again.")}}return <AppShell title="Raise an issue"><form className="card" onSubmit={submit} style={{maxWidth:680}}><p className="subtle">Describe what happened. Category and urgency are automatically suggested by the triage engine.</p><label>Issue title</label><input name="title" placeholder="e.g. Water leaking from bathroom tap" minLength={4} required/><label>What’s happening?</label><textarea name="description" placeholder="Add enough detail for the service team…" minLength={10} required rows={5}/><div className="split"><div><label>Location</label><input name="location" placeholder="Hostel Block A" required/></div><div><label>Building</label><input name="building" placeholder="Optional"/></div></div><label>Room number</label><input name="room" placeholder="Optional"/>{message&&<p className="card" style={{padding:10,margin:'10px 0',background:'#ecfdf3'}}>{message}</p>}<button className="button"><Send size={16}/>Submit complaint</button></form></AppShell>}
>>>>>>> 1b8878ef404f483e7609ab1c87da6c2e8c648546
